[pytest]
addopts = -ra --strict-markers
testpaths = test
norecursedirs = tmp test_outputs
filterwarnings =
    ignore::DeprecationWarning:numpy.*
    ignore::DeprecationWarning:faiss.*
    ignore::DeprecationWarning:.*SwigPy.*
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
markers =
    integration: mark tests as integration tests


