# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except ImportError:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class kbase_protein_query_module(object):
    """
    A KBase module: kbase_protein_query_module

    This module provides comprehensive protein query analysis capabilities using a modern,
    modular architecture with no backward compatibility:

    Authors: Vibhav Setlur
    Contact: https://kbase.us/contact-us/
    """

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)


    def run_protein_query_analysis(self, params, context=None):
        """
        Unified Protein Query Analysis Pipeline
        
        This method provides a single entry point for comprehensive protein analysis,
        supporting multiple input types and configurable analysis stages.
        
        :param params: instance of mapping from String to unspecified object
        :returns: instance of type "ProteinQueryAnalysisResults" -> structure: 
           parameter "job_id" of String, parameter "analysis_result_ref" of String, 
           parameter "summary" of String, parameter "input_parameters" of mapping from 
           String to unspecified object, parameter "start_time" of Float, 
           parameter "protein_count" of Int, parameter "stages_completed" of list of String, 
           parameter "report_name" of String, parameter "report_ref" of String, 
           parameter "shock_id" of String, parameter "shock_url" of String
        """
        return self._client.call_method('kbase_protein_query_module.run_protein_query_analysis',
                                        [params], self._service_ver, context)

    def get_available_analyses(self, context=None):
        """
        Return the registry of enabled analyses for front-end discovery.
        
        :returns: instance of type "GetAvailableAnalysesResults" -> structure: 
           parameter "available_analyses" of mapping from String to unspecified object, 
           parameter "summary" of String
        """
        return self._client.call_method('kbase_protein_query_module.get_available_analyses',
                                        [], self._service_ver, context)

    def status(self, context=None):
        """
        Return module health and version information for KBase runtime.
        
        :returns: instance of type "StatusResults" -> structure: 
           parameter "state" of String, parameter "message" of String, 
           parameter "version" of String, parameter "git_url" of String, 
           parameter "git_commit_hash" of String
        """
        return self._client.call_method('kbase_protein_query_module.status',
                                        [], self._service_ver, context)
